name: Cowpox
on: [push]
jobs:
  Cowpox:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - run: pip install Cowpox
    - run: Cowpox
    - uses: actions/upload-artifact@v2
      with:
        name: APK
        path: build/Cowpox/bin/outputs/apk/debug/project-debug.apk
